# [START app_yaml]

steps:
  - name: "morf"
    args: ["install"]
  - name: "morf"
    args: ["build:gcp"]

handlers:
  - url: /static
    static_dir: public

  - url: /.*
    script: auto
# [END app_yaml]
